### ISSUE TITLE
tty.clear is undefined

### ISSUE THREAD

**Issue by markfirmware** [ZystemOS/pluto#187]
I do not think aarch64/tty.init() is being called.

https://github.com/SamTebbs33/pluto/blob/c0d52ff2a8438c978905c5891fcb165e610da479/src/kernel/arch/aarch64/arch.zig#L32-L34

**Comment by SamTebbs33** [comment]
Good spot. I'll find something to blame this oversight on.

**Comment by markfirmware** [comment]
Resolved:

https://github.com/ZystemOS/pluto/blob/b9245df68b9f4bc64e9885f937cfb71c0e46edf4/src/kernel/arch/aarch64/arch.zig#L32-L34

**Comment by SamTebbs33** [comment]
#235
