### ISSUE TITLE
Finish AArch64 TTY

### ISSUE THREAD

**Issue by SamTebbs33** [ZystemOS/pluto#190]
The tty currently faults when writing pixels to it. #187 could be related

**Comment by faraazahmad** [comment]
I'm new to pluto so I'm not sure what 'faults when writing pixels to it' means. Can you please explain? Because `tty.print()` seems to be working fine in `kmain.zig`

**Comment by SamTebbs33** [comment]
@faraazahmad Thanks for mentioning that. I should have closed this after #246 was merged.
