### ISSUE TITLE
Open file "handle" leaks in VFS functions

### ISSUE THREAD

**Issue by iamgweej** [ZystemOS/pluto#220]
I might be missing something, but aren't there quite a few "leaks" in the VFS functions?

For example, in https://github.com/ZystemOS/pluto/blob/651e07146d07cd33b7cd57adde0bd428d334e613/src/kernel/filesystem/vfs.zig#L343 in case of an error nothing closes the `open`'d directory.

Am I missing something simple?

**Comment by SamTebbs33** [comment]
I don't believe you are missing anything! We (maybe just I) haven't been too considerate when it comes to cleaning up resources in the case of an error, so this is certainly a bug. Thanks for reporting this.

**Comment by iamgweej** [comment]
I think a fix is mostly comprised of adding appropriate `errdefer`s in all the relevant functions, I'll tackle it in a bit

**Comment by SamTebbs33** [comment]
Closed by #221
