### ISSUE TITLE
Initial PCI interface

### ISSUE THREAD

**Issue by DrDeano** [ZystemOS/pluto#244]
Create a basic interface for PCI: https://wiki.osdev.org/PCI. This allow the use of hard drives, network cards and other PCI devices. This issue will only relate to an initial set up where the kernel can list the current devices on the PCI bus.
Future issues will add functionality for attaching drivers to devices and providing a more details description of attached devices and handle PCI-to-PCI devices.

**Comment by SamTebbs33** [comment]
I agree that it would be nice to have simple listing functionality at first, then add driver assignment and a nice kernel-to-user interface later on (maybe via the VFS?).
