### ISSUE TITLE
What is the plan to get edit/compile/run zig working?

### ISSUE THREAD

**Issue by markfirmware** [ZystemOS/pluto#245]

**Comment by SamTebbs33** [comment]
Could you elaborate on what you mean?

**Comment by markfirmware** [comment]
Being able to edit and save a zig program, run the stage2 zig compiler, and then run the resulting binary. The vfs and elf execution features would be a part of this, but what else would be needed?

 https://kristoff.it/blog/zig-new-relationship-llvm might make it easier to do.

**Comment by SamTebbs33** [comment]
Oh you're talking about doing this in pluto. For this we at least need a simple text editor, a simple shell, user mode program execution (#50), ELF loading and execution (#230), the OS abstraction layer (#229) and probably a few more things that come could come with getting the compiler to work. The removal of LLVM as a necessary dependency will indeed make this much easier, I can't imagine how difficult or infeasible it would be get a port of LLVM working!

**Comment by markfirmware** [comment]
I see. Thanks.
