### ISSUE TITLE
Memory allocations in VFS fucntions

### ISSUE THREAD

**Issue by iamgweej** [ZystemOS/pluto#252]
I've been thinking about it, and I think we might run into some problems returning dynamically allocated memory from VFS functions. For example, every read operation from user mode will result in a dynamic allocation and deallocation (since it doesnt make much sense giving usermode kernel-allocated buffers).

I think we should consider converting to "out-parameter-pointer" signatures so we can avoid a lot of expensive allocations and deallocations, and memory copying functions

**Comment by SamTebbs33** [comment]
Good idea, that way you have the choice of data being allocated on the stack or heap. I suggest passing slices as a parameter.

**Comment by SamTebbs33** [comment]
Closed by #254
