### ISSUE TITLE
Zig always goes through entire build procedure with no changes

### ISSUE THREAD

**Issue by SamTebbs33** [ZystemOS/pluto#26]
When building the kernel, the entire build process is gone through even if no source files have changed so some investigation is needed. If this turns out to be an issue with zig and it is supposed to only build changed files then a bug report should opened. If we've done something wrong then the required changes should be made.

**Comment by faraazahmad** [comment]
Hi Is this issue fixed?

**Comment by SamTebbs33** [comment]
Hi @faraazahmad . I have spoken with Andrew (Zig founder) and he told me that this issue is due to Zig not keeping track of what has already been built (like Make does), so I believe we can close this issue as it's not a problem with pluto.
