### ISSUE TITLE
Testing suite issues

### ISSUE THREAD

**Issue by ghost** [ZystemOS/pluto#308]
A change of the behavior of tests has happened in at https://github.com/ziglang/zig/commit/59f9253d94331cedd4d0518250c8094a064f6cd2;

therefore, a big part of the testing suit is broken;

I will create a PR that will close this issue

**Comment by SamTebbs33** [comment]
Nice, thanks for tackling this.

**Comment by DrDeano** [comment]
As part of this issue and linked pull request, can all the `testing.expect*()` and `std.testing.expect*()` be renamed to just `expect*()` in the testing code so will import the functions at the top to make the code base more consistent.

**Comment by ghost** [comment]
> As part of this issue and linked pull request, can all the `testing.expect*()` and `std.testing.expect*()` be renamed to just `expect*()` in the testing code so will import the functions at the top to make the code base more consistent.

Sure

**Comment by SamTebbs33** [comment]
Closed by #310
