### ISSUE TITLE
Tidy mocking framework

### ISSUE THREAD

**Issue by DrDeano** [ZystemOS/pluto#69]
Once https://github.com/ziglang/zig/issues/313 is done

**Comment by cubranic** [comment]
ziglang/zig#313 is now closed, so the "blocked" label can be removed.

**Comment by SamTebbs33** [comment]
> [ziglang/zig#313](https://github.com/ziglang/zig/issues/313) is now closed, so the "blocked" label can be removed.

Thanks for the alert. I'll remove that now.
